# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: review-api

on:
  push:
    branches:
      - main
      - develop
    paths-ignore:
      - ".github/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./src/Glufs.Checkout.Api/Dockerfile
          push: true
          tags: |
            glufs/review-api:latest
            glufs/review-api:${{github.run_number}}

      - name: Allow extension installation
        uses: azure/CLI@v1
        with:
          inlineScript: az config set extension.use_dynamic_install=yes_without_prompt

      - name: Deploy preview
        uses: azure/CLI@v1
        if: github.ref == 'refs/heads/develop'
        with:
          inlineScript: |
            az containerapp revision copy -n review-preview-api-ca -g glufs-preview-rg -i glufs/review-api:${{github.run_number}} --revision-suffix run${{ github.run_number }}

      - name: Deploy prod
        uses: azure/CLI@v1
        if: github.ref == 'refs/heads/main'
        with:
          inlineScript: |
            az containerapp revision copy -n review-prod-api-ca -g glufs-prod-rg -i glufs/review-api:${{github.run_number}} --revision-suffix run${{ github.run_number }}
